### ISSUE TITLE
local repository with weird permissions

### ISSUE THREAD

**Issue by hboutemy** [flowlogix/flowlogix#525]
rebuilding recent releases shows Reproducible Builds issues: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/flowlogix/README.md

`commons-lang3-3.12.0.jar` and `primefaces-12.0.0-jakarta.jar` have weird permissions: cleaning local repository should fix the issue

**Comment by lprimak** [comment]
Ok, I blew away the maven repo on the release machine. Thank you

**Comment by hboutemy** [comment]
release 7.1 confirmed reproducible https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/flowlogix/README.md

well done!

**Comment by lprimak** [comment]
yay thank you!
